#.travis.yml

language: node_js
node_js:
  - "8.7"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli
  - npm install -g angular-cli-ghpages

script:
  - npm run ghdeploy

notifications:
  email:
    on_failure: change