#.travis.yml

language: node_js
node_js:
  - "8.7"

branches:
  only:
    - master
    - milwaukee-js-demo

before_script:
  - npm install -g @angular/cli
  - npm install -g angular-cli-ghpages

script:
  - npm run ci-test
  - npm run ci-coveralls
  - npm run ci-deploy

notifications:
  email:
    on_failure: change

sudo: required